name: 3dsegment_2
channels:
- conda-forge
- defaults
dependencies:
- python=3.13
- pip
- pip:
  - crc32c~=2.7.1
  - napari~=0.5.6
  - napari-plugin-manager~=0.1.4
  - nbformat~=5.10.4
  - numba~=0.61.0
  - PartSegCore_compiled_backend~=0.15.9
  - pipdeptree~=2.25.1
  - plotly~=6.0.0
  - pooch~=1.8.2
  - pyconify~=0.2.1
  - PyQt5~=5.15.11
  - scikit-learn~=1.6.1
  - seaborn~=0.13.2
  - tiffile~=2018.10.18
  - zarr~=3.0.2
