# Enhanced configuration for image processing pipeline with GUI definitions
mode: "ramified"

initial_segmentation:
  name: "Initial Segmentation"
  parameters:
    tubular_scales:
      label: "Tubular Scales"
      type: "float"
      value: 1
      min: 0.1
      max: 20
      step: 0.1
    min_size:
      label: "Minimum Size"
      type: "float"
      value: 300
      min: 0.5
      max: 10000
      step: 0.1
    anisotropy_normalization_degree:
      label: "Anisotropy Normalization Degree"
      type: "float"
      value: 1
      min: 0
      max: 1
      step: 1
    smooth_sigma:
      label: "Smooth Sigma"
      type: "float"
      value: 1.0
      min: 0.1
      max: 10
      step: 0.1
    min_cell_body_size:
      label: "Minimum Cell Body Size"
      type: "float"
      value: 300
      min: 0.5
      max: 10000
      step: 0.1
    sensitivity:
      label: "Sensitivity"
      type: "float"
      value: 1.0
      min: 0.0
      max: 1.0
      step: 0.1

refine_rois:
  name: "Refine ROIs"
  parameters:
    tubular_scales:
      label: "Tubular Scales"
      type: "float"
      value: 0.2
      min: 0.1
      max: 20
      step: 0.1
    min_size:
      label: "Minimum Size"
      type: "float"
      value: 300
      min: 0.5
      max: 10000
      step: 0.1
    anisotropy_normalization_degree:
      label: "Anisotropy Normalization Degree"
      type: "float"
      value: 1
      min: 0
      max: 1
      step: 1
    smooth_sigma:
      label: "Smooth Sigma"
      type: "float"
      value: 1.0
      min: 0.1
      max: 10
      step: 0.1
    min_cell_body_size:
      label: "Minimum Cell Body Size"
      type: "float"
      value: 300
      min: 0.5
      max: 10000
      step: 0.1
    sensitivity:
      label: "Sensitivity"
      type: "float"
      value: 1.0
      min: 0.0
      max: 1.0
      step: 0.1

calculate_features:
  name: "Calculate Features"

voxel_dimensions:
  x: 471.4
  y: 471.4
  z: 1