mode: ramified_2d
execute_raw_segmentation_ramified_2d:
  name: Execute Raw Segmentation (2D)
  parameters:
    tubular_scales:
      label: Tubular Scales (comma-sep floats)
      type: list
      value:
      - 0.3
      - 0.5
      element_type: float
    min_size:
      label: Minimum Size (Pixels, Raw Seg)
      type: int
      value: 1000
      min: 10
      max: 10000
      step: 10
    smooth_sigma:
      label: Smooth Sigma (Initial)
      type: float
      value: 1.1
      min: 0.1
      max: 10.0
      step: 0.1
    low_threshold_percentile:
      label: Low Threshold Percentile (Raw Seg)
      type: float
      value: 96.0
      min: 0.0
      max: 100.0
      step: 0.1
    high_threshold_percentile:
      label: High Threshold Percentile (Norm)
      type: float
      value: 100.0
      min: 0.0
      max: 100.0
      step: 0.1
    connect_max_gap_physical:
      label: Max Connect Gap (um)
      type: float
      value: 2.0
      min: 0.0
      max: 10.0
      step: 0.1
execute_trim_edges_ramified_2d:
  name: Execute Edge Trimming (2D)
  parameters:
    edge_trim_distance_threshold:
      label: Edge Trim Distance (um)
      type: float
      value: 0.1
      min: 0.0
      max: 20.0
      step: 0.1
    hull_boundary_thickness_phys:
      label: Hull Boundary Thickness (um)
      type: float
      value: 2.0
      min: 0.1
      max: 10.0
      step: 0.1
    brightness_cutoff_factor:
      label: Brightness Cutoff Factor
      type: float
      value: 1.5
      min: 0.0
      max: 10.0
      step: 0.1
    min_size_pixels:
      label: Min Size (Pixels, Post-Trim)
      type: int
      value: 120
      min: 0
      max: 5000
      step: 5
    smoothing_iterations:
      label: Hull Smoothing Iterations
      type: int
      value: 1
      min: 0
      max: 10
      step: 1
    heal_iterations:
      label: Heal Iterations (Post-Trim)
      type: int
      value: 1
      min: 0
      max: 10
      step: 1
execute_refine_rois_ramified_2d:
  name: Execute Refine ROIs (2D)
  parameters:
    ratios_to_process:
      label: Ratios to Process (Soma extraction; comma-sep floats)
      type: list
      value:
      - 0.3
      - 0.4
      - 0.5
      - 0.6
      element_type: float
    intensity_percentiles_to_process:
      label: Intensity Percentiles (Soma extraction; comma-sep integers)
      type: list
      value:
      - 99
      - 95
      - 90
      - 85
      - 80
      - 75
      - 70
      - 65
      - 60
      - 55
      - 50
      - 45
      - 40
      - 35
      - 30
      - 25
      - 20
      - 15
      - 10
      - 5
      - 1
      element_type: int
    smallest_quantile:
      label: Smallest Quantile (Soma extraction)
      type: float
      value: 0.05
      min: 0.0
      max: 1.0
      step: 0.01
    min_fragment_size:
      label: Min Fragment Size (Soma extraction)
      type: int
      value: 500
      min: 1
      max: 1000000
      step: 10
    core_volume_target_factor_lower:
      label: Soma Vol Factor (Soma extraction; Lower)
      type: float
      value: 0.1
      min: 0.01
      max: 1.0
      step: 0.01
    core_volume_target_factor_upper:
      label: Soma Vol Factor (Soma extraction; Upper)
      type: float
      value: 10.0
      min: 1.0
      max: 50.0
      step: 0.1
    erosion_iterations:
      label: Soma Erosion Iterations (Soma extraction)
      type: int
      value: 0
      min: 0
      max: 5
      step: 1
    min_physical_peak_separation:
      label: Soma Peak Separation (Soma extraction; um)
      type: float
      value: 20.0
      min: 1.0
      max: 20.0
      step: 0.1
    ref_vol_percentile_lower:
      label: Reference Volume Percentile (Soma extraction; Lower)
      type: int
      value: 5
      min: 0
      max: 100
      step: 1
    ref_vol_percentile_upper:
      label: Reference Volume Percentile (Soma extraction; Upper)
      type: int
      value: 95
      min: 0
      max: 100
      step: 1
    ref_thickness_percentile_lower:
      label: Reference Thickness Percentile (Soma extraction; Lower)
      type: int
      value: 5
      min: 0
      max: 100
      step: 1
    absolute_min_thickness_um:
      label: Soma Min Thickness (Soma extraction; um)
      type: float
      value: 1.5
      min: 0.5
      max: 10.0
      step: 0.1
    absolute_max_thickness_um:
      label: Soma Max Thickness (Soma extraction; um)
      type: float
      value: 10.0
      min: 5.0
      max: 30.0
      step: 0.1
    min_size_threshold:
      label: Min Size Threshold (Separate cells; um^3)
      type: float
      value: 20000.0
      min: 0.0
      max: 1000000.0
      step: 1.0
    max_seed_centroid_dist:
      label: Max Seed Merge Dist (Separate cells; um)
      type: float
      value: 20.0
      min: 0.0
      max: 10000.0
      step: 1.0
    min_path_intensity_ratio:
      label: Min Path Intensity Ratio (Separate cells)
      type: float
      value: 0.6
      min: 0.0
      max: 100.0
      step: 0.01
    min_local_intensity_difference:
      label: Min Local Intensity Difference (Separate cells)
      type: float
      value: 0.01
      min: 0.0
      max: 100.0
      step: 0.01
    local_analysis_radius:
      label: Local Analysis Radius (Separate cells; um)
      type: int
      value: 10
      min: 1
      max: 1000
      step: 1
    max_hole_size:
      label: Max Hole Size (Separate cells; um^2)
      type: int
      value: 0
      min: 0
      max: 1000000
      step: 1
execute_calculate_features_ramified_2d:
  name: Execute Feature Calculation (2D)
  parameters:
    prune_spurs_le_um:
      label: Prune Less then or equal (um)
      type: float
      value: 6.0
      min: 0
      max: 200
      step: 0.01
pixel_dimensions:
  x: 606.09
  y: 606.09
saved_state:
  segmentation_threshold: 0.01507481187582016