mode: ramified
initial_segmentation:
  name: Initial Segmentation
  parameters:
    tubular_scales:
      label: Tubular Scales (comma-sep floats)
      type: list
      value: [0.8, 1.0, 1.5, 2.0]
      element_type: float
    min_size:
      label: Minimum Size
      type: float
      value: 2000
      min: 0.5
      max: 10000
      step: 0.1
    smooth_sigma:
      label: Smooth Sigma
      type: float
      value: 1.3
      min: 0.1
      max: 10
      step: 0.1
    low_threshold_percentile:
      label: Low Threshold Percentile
      type: float
      value: 98
      min: 0
      max: 100
      step: 0.1
    high_threshold_percentile:
      label: High Threshold Percentile
      type: float
      value: 100
      min: 0
      max: 100
      step: 0.1
    brightness_cutoff_factor:
      label: Brightness Cutoff Factor
      type: float
      value: 100000
      min: 0.0
      max: 10000000
      step: 0.1
    edge_trim_distance_threshold:
      label: Edge Trim Distance Threshold
      type: float
      value: 4.5
      min: 0.0
      max: 10
      step: 0.1
refine_rois:
  name: Refine ROIs
  parameters:
    small_object_percentile:
      label: Small Object Percentile
      type: int
      value: 93
      min: 0
      max: 100
      step: 1
    thickness_percentile:
      label: Thickness Percentile
      type: int
      value: 92
      min: 0
      max: 100
      step: 1
    min_size_threshold:
      label: Minimum Size Threshold
      type: float
      value: 900
      min: 0.5
      max: 10000
      step: 0.1
calculate_features:
  name: Calculate Features
voxel_dimensions:
  x: 424.27
  y: 424.27
  z: 191.0
